/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesG;

import Clases.Empleado;
import Clases.Mesero;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose
 */
public class AgregarMesero1 extends javax.swing.JFrame {

    /**
     * Creates new form AgregarMesero1
     */
    public AgregarMesero1() {
        initComponents();
        this.setLocationRelativeTo(null);//para centrar la pantalla
        this.setTitle("AGREGAR MESERO");
        this.getRootPane().setDefaultButton(btn_agregarMesero);
    }

    private void bloquearNocturno() {
        //Se bloquea el checkpoint
        if (!check_nocturno.isSelected()) {

            check_diurno.setEnabled(true);

        } else {
            check_diurno.setEnabled(false);

        }
    }

    private void bloquearDiurno() {
        //Se bloquea el checkpoint
        if (!check_diurno.isSelected()) {
            check_nocturno.setEnabled(true);

        } else {
            check_nocturno.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nombreMesero = new LIB.FSTexFieldMD();
        idMesero = new LIB.FSTexFieldMD();
        nacimientoMesero = new LIB.FSTexFieldMD();
        jEImagePanel2 = new LIB.JEImagePanel();
        jEImagePanel1 = new LIB.JEImagePanel();
        jEImagePanel3 = new LIB.JEImagePanel();
        btn_agregarMesero = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        check_diurno = new javax.swing.JCheckBox();
        check_nocturno = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/backprueba2.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setDefaultCapable(false);
        btnRegresar.setFocusPainted(false);
        btnRegresar.setFocusable(false);
        btnRegresar.setRequestFocusEnabled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(243, 133, 17));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AGREGAR MESERO");

        nombreMesero.setForeground(new java.awt.Color(184, 42, 53));
        nombreMesero.setPlaceholder("Ingrese Nombre");
        nombreMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreMeseroActionPerformed(evt);
            }
        });

        idMesero.setForeground(new java.awt.Color(184, 42, 53));
        idMesero.setPlaceholder("Ingrese ID");
        idMesero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idMeseroKeyTyped(evt);
            }
        });

        nacimientoMesero.setForeground(new java.awt.Color(184, 42, 53));
        nacimientoMesero.setPlaceholder("Ingrese Fecha de nacimiento");

        jEImagePanel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PERSON.png"))); // NOI18N

        javax.swing.GroupLayout jEImagePanel2Layout = new javax.swing.GroupLayout(jEImagePanel2);
        jEImagePanel2.setLayout(jEImagePanel2Layout);
        jEImagePanel2Layout.setHorizontalGroup(
            jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jEImagePanel2Layout.setVerticalGroup(
            jEImagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ID.png"))); // NOI18N

        javax.swing.GroupLayout jEImagePanel1Layout = new javax.swing.GroupLayout(jEImagePanel1);
        jEImagePanel1.setLayout(jEImagePanel1Layout);
        jEImagePanel1Layout.setHorizontalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jEImagePanel1Layout.setVerticalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jEImagePanel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/calendar1.png"))); // NOI18N

        javax.swing.GroupLayout jEImagePanel3Layout = new javax.swing.GroupLayout(jEImagePanel3);
        jEImagePanel3.setLayout(jEImagePanel3Layout);
        jEImagePanel3Layout.setHorizontalGroup(
            jEImagePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jEImagePanel3Layout.setVerticalGroup(
            jEImagePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        btn_agregarMesero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar.png"))); // NOI18N
        btn_agregarMesero.setBorderPainted(false);
        btn_agregarMesero.setContentAreaFilled(false);
        btn_agregarMesero.setDefaultCapable(false);
        btn_agregarMesero.setFocusPainted(false);
        btn_agregarMesero.setFocusable(false);
        btn_agregarMesero.setRequestFocusEnabled(false);
        btn_agregarMesero.setVerifyInputWhenFocusTarget(false);
        btn_agregarMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarMeseroActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(243, 133, 17));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Agregar Mesero");

        status.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status.setText("Recuerde llenar todos los campos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(214, 40, 57));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Turno");

        check_diurno.setBackground(new java.awt.Color(255, 255, 255));
        check_diurno.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        check_diurno.setForeground(new java.awt.Color(214, 40, 57));
        check_diurno.setText("Diurno");
        check_diurno.setFocusPainted(false);
        check_diurno.setFocusable(false);
        check_diurno.setOpaque(false);
        check_diurno.setRequestFocusEnabled(false);
        check_diurno.setVerifyInputWhenFocusTarget(false);
        check_diurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_diurnoActionPerformed(evt);
            }
        });

        check_nocturno.setBackground(new java.awt.Color(255, 255, 255));
        check_nocturno.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        check_nocturno.setForeground(new java.awt.Color(214, 40, 57));
        check_nocturno.setText("Nocturno");
        check_nocturno.setFocusPainted(false);
        check_nocturno.setFocusable(false);
        check_nocturno.setOpaque(false);
        check_nocturno.setRequestFocusEnabled(false);
        check_nocturno.setVerifyInputWhenFocusTarget(false);
        check_nocturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_nocturnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 166, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEImagePanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEImagePanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEImagePanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nacimientoMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(check_diurno)
                                .addGap(63, 63, 63)
                                .addComponent(check_nocturno)))
                        .addGap(166, 166, 166))
                    .addComponent(btn_agregarMesero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombreMesero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEImagePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idMesero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEImagePanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jEImagePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nacimientoMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_diurno)
                    .addComponent(check_nocturno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btn_agregarMesero)
                .addGap(8, 8, 8)
                .addComponent(jLabel14)
                .addGap(40, 40, 40)
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void nombreMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreMeseroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreMeseroActionPerformed

    private void btn_agregarMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarMeseroActionPerformed
        // TODO add your handling code here:
        //Se agregan los datos a variables
        Empleado e = new Empleado();
        Mesero meserito = new Mesero();
        String turno = "";
        if (check_diurno.isSelected()) {
            turno = "DIURNO";
        }
        if (check_nocturno.isSelected()) {
            turno = "NOCTURNO";
        }
        //Se recolectan los datos
        String id = idMesero.getText();
        String nombre = nombreMesero.getText();
        String nacimiento = nacimientoMesero.getText();
        //Se verifica que todos los campos esten completos para poder agregar al mesero
        if (id.equals("") || nombre.equals("") || nacimiento.equals("") || turno.equals("")) {
            JOptionPane.showMessageDialog(null, "DEBE DE COMPLETAR LOS ESPACIOS");
        } else {
            meserito.AgregarDatos(idMesero, nombreMesero, nacimientoMesero, turno);
            e.agregarMesero(meserito);
            //Se verifica que se agregue bien
            e.desplegarEmpleado();
            status.setText("Mesero Agregado!");
            setText();
        }
    }//GEN-LAST:event_btn_agregarMeseroActionPerformed


    private void check_diurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_diurnoActionPerformed
        this.bloquearDiurno();
    }//GEN-LAST:event_check_diurnoActionPerformed

    private void check_nocturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_nocturnoActionPerformed
        this.bloquearNocturno();
    }//GEN-LAST:event_check_nocturnoActionPerformed

    private void idMeseroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idMeseroKeyTyped
       char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_idMeseroKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarMesero1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarMesero1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarMesero1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarMesero1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarMesero1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btn_agregarMesero;
    private javax.swing.JCheckBox check_diurno;
    private javax.swing.JCheckBox check_nocturno;
    private LIB.FSTexFieldMD idMesero;
    private LIB.JEImagePanel jEImagePanel1;
    private LIB.JEImagePanel jEImagePanel2;
    private LIB.JEImagePanel jEImagePanel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private LIB.FSTexFieldMD nacimientoMesero;
    private LIB.FSTexFieldMD nombreMesero;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables

    private void setText() {
        idMesero.setText("");
        nacimientoMesero.setText("");
        nombreMesero.setText("");
    }

}
